### PR TITLE
Do not trigger tests for .preset.json

### PR DESCRIPTION
**Pull request by Beilmann**
Added .preset.json to files that should not trigger tests

### Description

Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies. If there is a Git issue for the change, please link to it.

#### No release required

- [ ] Examples or tests (addition or updates of examples or tests)
- [ ] Documentation update
- [x] CI-related update (pipeline, etc.)
- [ ] Other changes that don't affect Terraform code

#### Release required

- [ ] Bug fix (patch release (`x.x.X`): Change that fixes an issue and is compatible with earlier versions)
- [ ] New feature (minor release (`x.X.x`): Change that adds functionality and is compatible with earlier versions)
- [ ] Breaking change (major release (`X.x.x`): Change that is likely incompatible with previous versions)

##### Release notes content

Replace this text with information that users need to know about the bug fixes, features, and breaking changes. This information helps the merger write the commit message that is published in the release notes for the module.

---

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### Merge actions for mergers

- Merge by using "Squash and merge".
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author.

    The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).

### CODE REVIEW

**Comment by ocofaigh** [comment]
@Beilmann Can you explain what exactly `.preset.json` files are used for in the code?

**Comment by surajsbharadwaj** [comment]
@ocofaigh https://github.com/terraform-ibm-modules/terraform-ibm-powervs-infrastructure/tree/main/examples/ibm-catalog/presets/slz_json_configs_for_powervs these are the presets.

Will be changing them to:
https://github.com/terraform-ibm-modules/terraform-ibm-powervs-infrastructure/tree/presets/examples/ibm-catalog/presets/slz-for-powervs

**Comment by ocofaigh** [comment]
Currently the presets are not used by the tests that run in the PR pipelines right? But perhaps maybe one day there might be a test that uses a `.presets.json` file as part of its tests? Remember this script is used for many repos (internal and external) so I need to be careful here that this change won't impact a pipeline for a different repo

**Comment by surajsbharadwaj** [comment]
@ocofaigh we have 2 files: rhel-vpc-pvs.preset.json and sles-vpc-pvs.preset.json
How about it can ignore pvs.preset.json ?
It is not being used in pipleine

**Comment by ocofaigh** [comment]
@surajsbharadwaj yes ok lets go with that then. Ignore `pvs.preset.json`

**Comment by surajsbharadwaj** [comment]
@ocofaigh i have added the prefix. Now it is pvs.preset.json

**Comment by surajsbharadwaj** [comment]
@ocofaigh should there be any * or? Because I just added pvs.preset.json

**Review by ocofaigh — APPROVED** [review]
i think this will work so approving and merging

**Pull request merged**
